[build]
base="/"
  command = "npm install && npm run build"
  publish = "public"

[[redirects]]
from="/"
to="/index.html"
status=200


[build.environment]
  NODE_VERSION = "16"

[context.production.environment]
  NODE_ENV = "production"
